### ISSUE TITLE
getDevices not finding anything, but lsusb shows VID:PID

### ISSUE THREAD

**Issue by petertorelli** [fpv-wtf/voc-web#3]
Running on Linux/Ubuntu + google-chrome, the navigator.usb.getDevices() promise returns nothing, but `lsusb` shows the existence of the VID:PID of the device. Is this a udev/group/permission issue?

**Comment by petertorelli** [comment]
Yup, udev rules.

**Comment by franzyke** [comment]
Can you be more specific? 

I tried copying this one https://github.com/fpvout/DigiView-SBC/blob/main/UDEV%20Rules/5-FPVGoggle.rules

does not work

I used `SUBSYSTEM=="usb", ATTRS{idVendor}=="2ca3", ATTR{idProduct}=="001f", MODE="0660", GROUP="plugdev"` and the permission issue is gone. 

But no image in my computer
