### ISSUE TITLE
DJI FPV Goggles V2 - NetworkError: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.

### ISSUE THREAD

**Issue by FreedomLabsIO** [fpv-wtf/voc-web#4]
I connected my Goggles V2 to the computer and launch the website fpv.wtf, a device called "PIGEON" appears and I click CONNECT, then this error appears:

`NetworkError: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.`

**Comment by j005u** [comment]
That usually means there's already another tab running.

voc-web will be retired soon, I recommend you try https://widefpv.com/ or https://live.fpvout.com/.
